export const ConstantTest = {
    test: "test"
}

export const authConstant = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILUAR: 'LOGIN_FAILUAR',
    
    USER_SOME_DATA_REQUEST: 'USER_SOME_DATA_REQUEST',
    USER_SOME_DATA_SUCCESS: 'USER_SOME_DATA_SUCCESS',
    USER_SOME_DATA_FAILUAR: 'USER_SOME_DATA_FAILUAR',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILUAR: 'LOGOUT_FAILUAR',

    CLEAN_UP_AUTH: 'CLEAN_UP_AUTH',
}
export const userDataConstant = {
    UPDATE_USER_Data_REQUEST: 'UPDATE_USER_Data_REQUEST',
    UPDATE_USER_Data_SUCCESS: 'UPDATE_USER_Data_SUCCESS',
    UPDATE_USER_Data_FAILUAR: 'UPDATE_USER_Data_FAILUAR',


    GET_USER_Data_REQUEST: 'GET_USER_Data_REQUEST',
    GET_USER_Data_SUCCESS: 'GET_USER_Data_SUCCESS',
    GET_USER_Data_FAILUAR: 'GET_USER_Data_FAILUAR',

    CLEAN_UP_USER_DATA: 'CLEAN_UP_USER_DATA',

}
export const bookCatConstant = {
    GET_BOOK_CAT_REQUEST: 'GET_BOOK_CAT_REQUEST',
    GET_BOOK_CAT_SUCCESS: 'GET_BOOK_CAT_SUCCESS',
    GET_BOOK_CAT_FAILUAR: 'GET_BOOK_CAT_FAILUAR',

    CLEAN_UP_CAT : "CLEAN_UP_CAT"
}

export const bookConstant = {
    SET_BOOK_REQUEST: 'SET_BOOK_REQUEST',
    SET_BOOK_SUCCESS: 'SET_BOOK_SUCCESS',
    SET_BOOK_FAILUAR: 'SET_BOOK_FAILUAR',

    GET_BOOK_REQUEST: 'GET_BOOK_REQUEST',
    GET_BOOK_SUCCESS: 'GET_BOOK_SUCCESS',
    GET_BOOK_FAILUAR: 'GET_BOOK_FAILUAR',

    IS_FOR_EDIT_OR_NOT: "IS_FOR_EDIT_OR_NOT",
    CLEAN_UP_USER_DATA: 'CLEAN_UP_USER_DATA',

    UPLOAD_IMG_BOOK_REQUEST: 'UPLOAD_IMG_BOOK_REQUEST',
    UPLOAD_IMG_BOOK_SUCCESS: 'UPLOAD_IMG_BOOK_SUCCESS',
    UPLOAD_IMG_BOOK_FAILUAR: 'UPLOAD_IMG_BOOK_FAILUAR',

    DELETE_BOOK_REQUEST: 'DELETE_BOOK_REQUEST',
    DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
    DELETE_BOOK_FAILUAR: 'DELETE_BOOK_FAILUAR',


    CLEAN_UP_BOOK: 'CLEAN_UP_BOOK',

}

export const booksConstant = {
    SET_BOOK_REQUEST: 'SET_BOOK_REQUEST',
    SET_BOOK_SUCCESS: 'SET_BOOK_SUCCESS',
    SET_BOOK_FAILUAR: 'SET_BOOK_FAILUAR',

    GET_BOOKS_REQUEST: 'GET_BOOKS_REQUEST',
    GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
    GET_BOOKS_FAILUAR: 'GET_BOOKS_FAILUAR',

    LOAD_MORE_USER_BOOKS_REQUEST: 'LOAD_MORE_USER_BOOKS_REQUEST',
    LOAD_MORE_USER_BOOKS_SUCCESS: 'LOAD_MORE_USER_BOOKS_SUCCESS',
    LOAD_MORE_USER_BOOKS_FAILUAR: 'LOAD_MORE_USER_BOOKS_FAILUAR',

    GET_ALL_BOOKS_REQUEST: 'GET_ALL_BOOKS_REQUEST',
    GET_ALL_BOOKS_SUCCESS: 'GET_ALL_BOOKS_SUCCESS',
    GET_ALL_BOOKS_FAILUAR: 'GET_ALL_BOOKS_FAILUAR',

    CLEAN_UP_BOOKS_DATA: 'CLEAN_UP_BOOKS_DATA',

    LOAD_MORE_BOOKS_REQUEST: "LOAD_MORE_BOOKS_REQUEST",
    LOAD_MORE_BOOKS_SUCCESS: "LOAD_MORE_BOOKS_SUCCESS",
    LOAD_MORE_BOOKS_FAILUAR: "LOAD_MORE_BOOKS_FAILUAR",
}


export const reqBookConstants = {
    SET_REQ_BOOK_DATA_REQUEST: 'SET_REQ_BOOK_DATA_REQUEST',
    SET_REQ_BOOK_DATA_SUCCESS: 'SET_REQ_BOOK_DATA_SUCCESS',
    SET_REQ_BOOK_DATA_FAILUAR: 'SET_REQ_BOOK_DATA_FAILUAR',
    
    CLEAN_UP_REQUESTS: 'CLEAN_UP_REQUESTS',
    
    GET_BOOK_REQUESTS_REQUEST: 'GET_BOOK_REQUESTS_REQUEST',
    GET_BOOK_REQUESTS_SUCCESS: 'GET_BOOK_REQUESTS_SUCCESS',
    GET_BOOK_REQUESTS_FAILUAR: 'GET_BOOK_REQUESTS_FAILUAR',


    GET_ALL_REQUESTS_REQUEST: 'GET_ALL_REQUESTS_REQUEST',
    GET_ALL_REQUESTS_SUCCESS: 'GET_ALL_REQUESTS_SUCCESS',
    GET_ALL_REQUESTS_FAILUAR: 'GET_ALL_REQUESTS_FAILUAR',
    
    LOAD_MORE_REQUESTS_REQUEST: 'LOAD_MORE_REQUESTS_REQUEST',
    LOAD_MORE_REQUESTS_SUCCESS: 'LOAD_MORE_REQUESTS_SUCCESS',
    LOAD_MORE_REQUESTS_FAILUAR: 'LOAD_MORE_REQUESTS_FAILUAR',

    CLEAN_UP_ALL_REQUESTS: 'CLEAN_UP_ALL_REQUESTS',
    
}